# Generated by Django 5.2.7 on 2025-10-05 22:45

import django.db.models.deletion
import universidad.models.alumno
import universidad.models.docente
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_secundario', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(max_length=128)),
                ('numero_registro', models.CharField(default=universidad.models.alumno.generar_registro, editable=False, max_length=6, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('numero_registro', models.CharField(default=universidad.models.docente.generar_registro_docente, editable=False, max_length=6, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('certificable', models.BooleanField(default=False)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('modo_prueba', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='universidad.area')),
                ('docente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='universidad.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='universidad.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('material', models.FileField(blank=True, null=True, upload_to='materiales/')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='universidad.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('es_trial', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='universidad.alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='universidad.curso')),
            ],
            options={
                'unique_together': {('alumno', 'curso')},
            },
        ),
    ]
