# Generated by Django 5.1.7 on 2025-10-05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0001_initial'),  # Ajusta según tu última migración
    ]

    def insert_roles(self, schema_editor):
        Group = self.get_model('auth', 'Group')

        roles = ["Administrador", "Docente", "Alumno"]
        for role in roles:
            Group.objects.get_or_create(name=role)

    operations = [
        migrations.RunPython(insert_roles, atomic=True),
    ]
