# Generated by Django 5.1.7 on 2025-10-05
from django.contrib.auth.hashers import make_password
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0003_add_permissions'),
    ]

    def create_admin_user(self, schema_editor):
        User = self.get_model('auth', 'User')
        Group = self.get_model('auth', 'Group')

        admin_group = Group.objects.get(name='Administrador')

        # Si ya existe el usuario admin, no volver a crearlo
        user, created = User.objects.get_or_create(
            username='admin',
            defaults={
                'email': 'admin@virtualacademy.com',
                'is_staff': True,
                'is_superuser': True,
                'password': make_password('123456789')
            }
        )

        # Asignar grupo Administrador
        user.groups.add(admin_group)

    operations = [
        migrations.RunPython(create_admin_user, atomic=True),
    ]
