# Generated by Django 5.2.7 on 2025-10-09 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0005_alumno_groups_alumno_is_active_alumno_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='nombre_completo',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='password',
        ),
        migrations.AddField(
            model_name='docente',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docente_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
