# Generated by Django 5.2.7 on 2025-10-09 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0006_remove_docente_email_remove_docente_nombre_completo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='docente_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
