# Generated by Django 5.2.7 on 2025-10-09 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0007_alter_docente_user'),
        ('universidad', '0008_fix_permissions'),
    ]

    operations = [
    ]
