# Generated by Django 5.2.7 on 2025-10-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0009_merge_0007_alter_docente_user_0008_fix_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='numero_registro',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
    ]
