# Generated by Django 5.2.7 on 2025-10-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0012_fix_docente_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
