# Generated by Django 5.2.7 on 2025-10-11 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0013_seccion_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='photo_profile',
            field=models.ImageField(blank=True, null=True, upload_to='curso_portadas/'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='modo_prueba',
            field=models.BooleanField(default=True),
        ),
    ]
