# Generated by Django 5.2.7 on 2025-10-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0014_curso_photo_profile_alter_curso_modo_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='photo_profile',
            field=models.ImageField(blank=True, null=True, upload_to='alumnos_fotos/'),
        ),
        migrations.AddField(
            model_name='docente',
            name='photo_profile',
            field=models.ImageField(blank=True, null=True, upload_to='docentes_fotos/'),
        ),
    ]
