# Generated by Django 5.2.7 on 2025-11-06 21:12

import universidad.models.alumno
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0015_alumno_photo_profile_docente_photo_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='area_portadas/'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='photo_profile',
            field=models.ImageField(blank=True, default='alumnos_fotos/profile_icon.png', null=True, upload_to=universidad.models.alumno.ruta_foto_perfil),
        ),
    ]
